experiments:
  - name: "louvain_V500_C100_N16"
    iterations: 30
    ground_truth_generation:
      random_seed: 42
      number_of_vertices: 500
      number_of_ground_truth_communities: 100
    noise_injection:
      number_of_correct_observations: 16.0
    community_detection:
      algorithm: "louvain"

  - name: "nclusterbox_V500_C100_N16"
    iterations: 30
    ground_truth_generation:
      random_seed: 42
      number_of_vertices: 500
      number_of_ground_truth_communities: 100
    noise_injection:
      number_of_correct_observations: 16.0
    community_detection:
      algorithm: "nclusterbox"

  - name: "louvain_V500_C100_N8"
    iterations: 30
    ground_truth_generation:
      random_seed: 42
      number_of_vertices: 500
      number_of_ground_truth_communities: 100
    noise_injection:
      number_of_correct_observations: 8.0
    community_detection:
      algorithm: "louvain"

  - name: "nclusterbox_V500_C100_N8"
    iterations: 30
    ground_truth_generation:
      random_seed: 42
      number_of_vertices: 500
      number_of_ground_truth_communities: 100
    noise_injection:
      number_of_correct_observations: 8.0
    community_detection:
      algorithm: "nclusterbox"

  - name: "louvain_V500_C100_N4"
    iterations: 30
    ground_truth_generation:
      random_seed: 42
      number_of_vertices: 500
      number_of_ground_truth_communities: 100
    noise_injection:
      number_of_correct_observations: 4.0
    community_detection:
      algorithm: "louvain"

  - name: "nclusterbox_V500_C100_N4"
    iterations: 30
    ground_truth_generation:
      random_seed: 42
      number_of_vertices: 500
      number_of_ground_truth_communities: 100
    noise_injection:
      number_of_correct_observations: 4.0
    community_detection:
      algorithm: "nclusterbox"

  - name: "louvain_V500_C100_N2"
    iterations: 30
    ground_truth_generation:
      random_seed: 42
      number_of_vertices: 500
      number_of_ground_truth_communities: 100
    noise_injection:
      number_of_correct_observations: 2.0
    community_detection:
      algorithm: "louvain"

  - name: "nclusterbox_V500_C100_N2"
    iterations: 30
    ground_truth_generation:
      random_seed: 42
      number_of_vertices: 500
      number_of_ground_truth_communities: 100
    noise_injection:
      number_of_correct_observations: 2.0
    community_detection:
      algorithm: "nclusterbox"

  - name: "louvain_V500_C100_N1"
    iterations: 30
    ground_truth_generation:
      random_seed: 42
      number_of_vertices: 500
      number_of_ground_truth_communities: 100
    noise_injection:
      number_of_correct_observations: 1.0
    community_detection:
      algorithm: "louvain"

  - name: "nclusterbox_V500_C100_N1"
    iterations: 30
    ground_truth_generation:
      random_seed: 42
      number_of_vertices: 500
      number_of_ground_truth_communities: 100
    noise_injection:
      number_of_correct_observations: 1.0
    community_detection:
      algorithm: "nclusterbox"
